name: Build and deploy Streamlit frontend to Azure Web App - StreamFront

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r frontend/requirements.txt

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: frontend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-app
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FE97AAB77A1D4E92A36A28A07BC873A9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_72EC6246679B479AA09842692CDDF2B5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6AE5003C15094098820B5128ACD5D556 }}

      # Delay to avoid SCM restart killing deployment
      - name: Wait before deploy
        run: sleep 20

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'StreamFront'
          slot-name: 'Production'
          package: .
